### PR TITLE
Rework AST

### PR DESCRIPTION
**Pull request by pshc**
I had a lot of free time on my hands yesterday (5 hour plane ride) and while trying to knock out some smaller bugs I noticed we have structural AST issues. Not sure yet if I made it better or worse.

- [x] Introduce `DoStatement` for do syntax, fixing `let` codegen (#34)
- [x] Parsing `where` closer to how I understand it, at least
- [x] List comprehensions
- [x] Infix operators (#48)
- [x] Using patterns directly in `<pat> = <expr>` again
- [x] Handle the very ambiguous `pat <- expr` using conv_expr_to_pat
- [x] `let a = 2 in ...` expressions (#45)
- [x] `where` issue in corrode: search for `wrapArgv`, it should be in the `where`
- [x] `<-` in guards (?)
- [x] `|` in let?

### CODE REVIEW

**Comment by tcr** [comment]
This list would handle a lot of the remaining edge cases, so thank you for tackling them!

The whitespace logic is obviously throwing a wrench in these fixes, and I actually dealt with these issues before. The unsatisfactory result was parsing "where" clauses as any old statement and asserting that they are the last statement, but this prevents successive let clauses or let ... in from being parsed right. I think this is a step in the right direction, I'll try to review more in depth tomorrow.

**Comment by tcr** [comment]
The `let` ... `where` ... `wrapArgv` issue looks slightly worse, the let statement seems to only encapsulate one statement:

```

     ;let{ ret = Rust.VarName "cmV0"
      };emitItems [Rust.Item [] Rust.Private (
         Rust.Function [] "bWFpbg==" [] (Rust.TypeName "KCk=") (statementsToBlock (
             setup ++
             [ bind Rust.Immutable ret $
                 Rust.UnsafeExpr $ Rust.Block [] $ Just $
                 call realName args ] ++
             exprToStatements (call "OjpzdGQ6OnByb2Nlc3M6OmV4aXQ=" [Rust.Var ret])
         )))]
     }where{



        bind mut var val = Rust.Let mut var Nothing (Just val)
     
 
 
         ;call fn args = Rust.Call (Rust.Var (Rust.VarName fn)) args
     
 
 
         ;chain method args obj = Rust.MethodCall obj (Rust.VarName method) args
     
 
 
     }wrapArgv [] = return ([], [])
```

I'm unsure how it parses on master, I should check that next. (This was generated by uncommenting the two lines in `test_no_regressions` that write out `test.txt`.)

**Comment by pshc** [comment]
Forgive me if I'm wrong but I think `let { ret = Rust.VarName "cmV0" };` is correct?

**Comment by pshc** [comment]
What I'm wondering is why we get

```
Error: Unrecognized token `wrapArgv`:
774 |
775 |
776 |      }wrapArgv [] = return ([], [])
```

does there need to be a semicolon before `wrapArgv` or something?

**Comment by pshc** [comment]
Rebased on master. Time for another long plane ride.

**Comment by tcr** [comment]
Yes, you're right. (I need to pick up a book...) I believe it's a bug in the LHS stripper. Looking into it now.

**Comment by tcr** [comment]
Fixed the wrapArgv issue! I tried to knock out the rest of your list also, feel free to restructure any of those solutions.

There's only three or so remaining issues before this PR passes tests again. Can't wait to have proper let and where output in the generated code.

**Comment by tcr** [comment]
Merge whenever you're interested.

**Comment by pshc** [comment]
Whoaaa! Awesome! 🥇

**Pull request merged**
