### PR TITLE
Pattern/type work

### PR DESCRIPTION
**Pull request by pshc**
Tried to split patterns from types.

The output has lost quite a few files from this, unfortunately. I think the arrow patterns are primarily to blame? I could use some help in parsing those.

Addresses #5.

### CODE REVIEW

**Comment by tcr** [comment]
Nice. I'll pull this tonight and help fix the regressions.

**Comment by pshc** [comment]
Looks like the main issue is that I put record syntax in the wrong place, heh.

**Comment by pshc** [comment]
Okay! Other than AstAnalysis, which seems to be broken on a `where`, I think we're back to parity.

I think I'll rebase and split up this branch and make a new PR or two for it.

**Comment by pshc** [comment]
Superseded by #10 and #11.

**Pull request closed without merging**
